# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RUChatDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RUChatDemo


 pod 'Hyphenate', '~> 3.3.1'


 pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git', :tag => ‘3.3.1’
pod 'Masonry', '~> 1.0.0'

end
